package cz.vutbr.fit.simulatormanager.types;

public enum PageType {
	HOME, //
	MANAGE_SIMULATOR_MODELS, //
	MANAGE_SIMULATORS, //
	CHOOSE_SIMULATION, //
	CONFIGURATIONS, //
	VIEW_PAST_SIMULATION, //
	VIEW_RUNNING_SIMULATION, //
	VIEW_SIMULATION//

}
